[package]
name = "typst-ts-renderer"
version = "0.1.6"
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
description = "Render Typst documents in browser."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[lib]
crate-type = ["cdylib"]

[dependencies]
typst-ts-core = "0.1"
typst-ts-compiler = { version = "0.1", default-features = false, features = ["web"] }
typst-ts-canvas-exporter = { version = "0.1", optional = true }
typst-ts-raster-exporter = { version = "0.1", optional = true }

typst = "0.3.0"
typst-library = "0.3.0"
comemo = "0.2"

once_cell = "1.17.1"
siphasher = "0.3.10"
elsa = "1.8.0"

pollster = "0.3.0"
tiny-skia = "0.9.0"

serde_json = { version = "1.0.95", optional = true }
serde = { version = "1.0.159", optional = true }
rmp-serde = { version = "1.1.1", optional = true }
byteorder = "1.4.3"

# Everything to do with wasm
wasm-bindgen = { version = "^0.2" }
js-sys = "^0.3"
wasm-bindgen-futures = "^0.4"
serde-wasm-bindgen = "^0.5"
web-sys = { version = "^0.3", features = ["console", "Window", "Blob", "ImageData"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
web-sys = { version = "^0.3", features = ["console", "Performance", "PerformanceTiming", "Window", "Blob", "ImageData", "Document", "HtmlCanvasElement"] }

[features]
full = ["serde_json", "serde_rmp", "render_raster", "render_canvas"]
serde_json = ["dep:serde_json"]
serde_rmp = ["dep:serde", "dep:rmp-serde"]
render_raster = ["dep:typst-ts-raster-exporter"]
render_canvas = ["dep:typst-ts-canvas-exporter", "web-sys/CanvasRenderingContext2d"]
default = ["full"]
web = ["render_canvas"]
